version: 2
updates:

  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the `crates.io` for updates every day (weekdays)
    schedule:
      interval: "daily"
      
