name: Node.js CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: [ 12.x ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            #            -   run: npm ci    # use instead of install if we choose to commit the `package-lock.json`
            -   run: npm install
            -   run: npm run build --if-present
    #            -   run: npm test
    #                env:
    #                    CI: true

    codefmt:
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   run: npm install
            -   run: npm run prettier -- --check .
